baseURL = "https://datatogether.org"
title = "Data Together"
theme = "datatogether"

metaDataFormat = "toml"
relativeURLs = true
languageCode = "en-us"
defaultContentLanguage = "en"

[params]
  # ExtraCssFiles = [ "/css/override.css" ] # In your `static/css`, add/remove files as necessary.
  domain = "datatogether.org"
  author = "Data Together"
  title = "Data Together"
  description = "Communities stewarding data together"
  github = "datatogether"
  twitter = "data_together"
  email = ""
  favicon = ""
  cacheBuster = true
  dateForm = "Jan 2, 2006"
  dateFormFull = "Mon Jan 2 2006 15:04:05 MST"
